version: "3"
services:
  linbpq:
    build:
      context: /opt/docker/compose/bpq/docker-linbpq
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8081:8081
    # Uncomment what is needed below if you are using a serial-connected TNC
    #devices:
      # Map serial devices from the host into the container (adjust as needed)
      # - "/dev/ttyUSB0:/dev/ttyACM0"
    volumes:
      # We are going to mount the entire linbpq directory.    I don't want traffic, mail configs, chat configs, etc... lost in a container move.
      - /opt/docker/containerdata/bpq:/opt/linbpq
