version: "3"
services:
  linbpq:
    image: ve3lsr/linbpq
    build: .
    restart: always
    ports:
      - 8081:80
    devices:
      # Map serial devices from the host into the container (adjust as needed)
      - "/dev/ttyUSB0:/dev/ttyACM0"
      # Map audio devices in to the container (assumes PulseAudio is *not* in use)
      - "/dev/snd:/dev/snd"
    volumes:
      # We are going to mount the entire linbpq directory.    I don't want traffic, mail configs, chat configs, etc... lost in a container move.  Hopefully the build script drops the right stuff in...
      - /srv/linbpq:/opt/linbpq
